logging:
  level:
    org:
      springframework:
        web: DEBUG

server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: api
  h2:
    console:
      enabled: true